baseURL: "https://blog.wujunlin.top/" # ç»‘å®šçš„åŸŸå
title: Wu's Blog # ä¸»é¡µä¸‹æ˜¾ç¤ºçš„æµè§ˆå™¨æ ‡é¢˜
paginate: 5
theme: PaperModX # ä¸»é¢˜åå­—ï¼Œå’Œthemesæ–‡ä»¶å¤¹ä¸‹çš„ä¸€è‡´
languageCode: zh-cn # en-us
defaultContentLanguage: "zh" # æœ€é¡¶éƒ¨é¦–å…ˆå±•ç¤ºçš„è¯­è¨€é¡µé¢
# NOTE remove this line if you copy exampleSite outof hugo-PaperModX
# themesdir: ../..

enableInlineShortcodes: true
enableRobotsTXT: true # å…è®¸çˆ¬è™«æŠ“å–åˆ°æœç´¢å¼•æ“ï¼Œå»ºè®® true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
hasCJKLanguage: true # å­—æ•°ç»Ÿè®¡åŒ…å«æ±‰å­—

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Wu's Blog
  description: "Wu's Blog"
  keywords: [Blog, Portfolio, PaperMod]
  author: "WuJunlin"
  defaultTheme: auto # dark, light
  disableAnchoredHeadings: true
  mainSections:
    - docs
    - posts
  images: [""]
  DateFormat1: "2006-01-02 15:04"
  DateFormat: "2006-01-02"
  useCustomAnalytics: true
  ShowLastMod: true
  ShowAuthor: true
  enableCoverzoom: false # æ˜¯å¦å¼€å¯å°é¢å›¾ç¼©å°

  logo: # ä¸»é¡µå·¦ä¸Šè§’çš„ä¿¡æ¯
    text: "Wu's Bloggggg"
    icon: https://icon-1302751266.cos.ap-chengdu.myqcloud.com/cloud.png
    iconHeight: 35

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # disableThemeToggle: true
  ShowShareButtons: true
  displayFullLangName: true
  ShowToc: true
  TocOpen: true
  TocSide: "right"
  EnableInstantClick: true
  EnableImageZoom: true
  ShowReadingTime: true # æ˜¾ç¤ºé˜…è¯»æ—¶é—´
  # ShareButtons: ["linkedin", "twitter"]
  ShowPostNavLinks: true # åº•éƒ¨æ˜¾ç¤ºä¸‹ä¸€ç¯‡æ ‡è®°
  ShowBreadCrumbs: true #å¸–å­æ ‡é¢˜ä¸Šæ–¹æ·»åŠ é¢åŒ…å±‘å¯¼èˆªä»¥æ˜¾ç¤ºå°èŠ‚å’Œå¯¼èˆªåˆ°ä¸»é¡µ 
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  page_view_conter: true

  # commentSystems:
  #   disqus:
  #     shortname: reorx
  #   remark42:
  #     url: https://remark42.reorx.com
  #     site: reorx.github.io
  #   telegramWidget:
  #     channel: reorx_share
  #     accentColor: "9077e1"
  #     limit: 20
  # defaultCommentSystems:
  #   remark42: true

  # home-info mode
  homeInfoParams:
    Title: "å­¦ç€æ¥å— è¯•ç€æ”¹å˜ \U0001F44B"
    Content: Welcome to my bloggggg

  profileMode:
    enabled: false
    title: PaperModX
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: /archives/
      - name: Tags
        url: /tags/

  socialIcons:
    - name: github
      url: "https://github.com/O1SL"
    - name: rss
      url: "index.xml" 

  # editPost:
  #   URL: "https://github.com/reorx/hugo-PaperModX/tree/exampleSite/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # assets:
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: Archives
      name: "æ–‡æ¡£ ğŸ“„"
      url: /archives/ 
      weight: 10
    - identifier: Tags
      name: "æ ‡ç­¾ ğŸ“"
      url: /tags/
      weight: 15
    - identifier: Search
      name: "æœç´¢ ğŸ”"
      url: /Search/
      weight: 20

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

# taxonomies:
#   category: categories
#   tag: tags
#   series: series 

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
